import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // 使用 CSS 变量以支持主题切换
        'background': 'var(--color-background)',
        'sidebar-canvas': 'var(--color-sidebar-canvas)',
        'surface-lowest': 'var(--color-surface-lowest)',
        'surface-low': 'var(--color-surface-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-high': 'var(--color-surface-high)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-container-low': 'var(--color-surface-low)',
        'surface': 'var(--color-background)',
        'surface-variant': 'var(--color-surface-container)',
        'surface-dim': 'var(--color-background)',
        'surface-tint': 'var(--color-primary)',
        'surface-container-highest': 'var(--color-surface-bright)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-lowest': 'var(--color-surface-lowest)',
        
        'primary': 'var(--color-primary)',
        'primary-dim': 'var(--color-primary-dim)',
        'primary-container': 'var(--color-surface-high)',
        'primary-fixed': 'var(--color-primary)',
        'primary-fixed-dim': 'var(--color-primary-dim)',
        'on-primary': 'var(--color-on-primary)',
        'on-primary-container': 'var(--color-on-surface)',
        'on-primary-fixed': 'var(--color-on-primary)',
        'on-primary-fixed-variant': 'var(--color-on-surface-variant)',
        
        'secondary': 'var(--color-on-surface-variant)',
        'secondary-dim': 'var(--color-on-surface-variant)',
        'secondary-container': 'var(--color-surface-container)',
        'secondary-fixed': 'var(--color-surface-high)',
        'secondary-fixed-dim': 'var(--color-surface-container)',
        'on-secondary': 'var(--color-on-surface)',
        'on-secondary-container': 'var(--color-on-surface)',
        'on-secondary-fixed': 'var(--color-on-surface)',
        'on-secondary-fixed-variant': 'var(--color-on-surface-variant)',
        
        'tertiary': 'var(--color-surface-lowest)',
        'tertiary-dim': 'var(--color-surface-low)',
        'tertiary-container': 'var(--color-surface-low)',
        'tertiary-fixed': 'var(--color-surface-container)',
        'tertiary-fixed-dim': 'var(--color-surface-high)',
        'on-tertiary': 'var(--color-on-surface-variant)',
        'on-tertiary-container': 'var(--color-on-surface-variant)',
        'on-tertiary-fixed': 'var(--color-on-surface)',
        'on-tertiary-fixed-variant': 'var(--color-on-surface-variant)',
        
        'error': 'var(--color-error)',
        'error-dim': 'var(--color-error-text)',
        'error-container': 'var(--color-error-bg)',
        'on-error': '#ffffff',
        'on-error-container': 'var(--color-error-text)',
        
        'outline': 'var(--color-on-surface-variant)',
        'outline-variant': 'var(--color-outline-variant)',
        
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'on-background': 'var(--color-on-surface)',
        
        'inverse-surface': 'var(--color-surface-lowest)',
        'inverse-on-surface': 'var(--color-on-surface)',
        'inverse-primary': 'var(--color-primary)',
        
        // 状态颜色
        'status-success': 'var(--color-success)',
        'status-success-bg': 'var(--color-success-bg)',
        'status-success-text': 'var(--color-success-text)',
        'status-info': 'var(--color-info)',
        'status-info-bg': 'var(--color-info-bg)',
        'status-info-text': 'var(--color-info-text)',
        'status-warning': 'var(--color-warning)',
        'status-warning-bg': 'var(--color-warning-bg)',
        'status-warning-text': 'var(--color-warning-text)',
        'status-error': 'var(--color-error)',
        'status-error-bg': 'var(--color-error-bg)',
        'status-error-text': 'var(--color-error-text)',
        'status-neutral': 'var(--color-neutral)',
        'status-neutral-bg': 'var(--color-neutral-bg)',
        'status-neutral-text': 'var(--color-neutral-text)',

        'role-teacher-bg': 'var(--color-role-teacher-bg)',
        'role-teacher-text': 'var(--color-role-teacher-text)',
        'role-author-bg': 'var(--color-role-author-bg)',
        'role-author-text': 'var(--color-role-author-text)',
      },
      fontFamily: {
        inter: ['var(--font-inter)'],
        headline: ['var(--font-plus-jakarta)', 'var(--font-inter)'],
        display: ['var(--font-plus-jakarta)', 'var(--font-inter)'],
        body: ['var(--font-inter)'],
        label: ['var(--font-inter)'],
        sans: ['var(--font-inter)'],
        mono: ['var(--font-jetbrains-mono)'],
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        lg: '0.625rem',
        xl: '0.875rem',
        '2xl': '1.125rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
export default config
